model:
  huggingface: "QuantTrio/Qwen3-Coder-30B-A3B-Instruct-AWQ"

engine:
  llm:
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    gpu_memory_utilization: 0.8
    context_length: 102400
    max_concurrent_requests: 16
    vllm:
      image: "vllm/vllm-openai:v0.17.0"
      # for copilot
      # extra_args: "--enable-auto-tool-choice --tool-call-parser hermes"
      extra_args: "--dtype bfloat16 --kv-cache-dtype fp8 --max-num-batched-tokens 4096 --enable-prefix-caching --enable-auto-tool-choice --tool-call-parser qwen3_coder"

benchmark:
  max_concurrency: 4
  num_prompts: 80
  random_input_len: 4000
  random_output_len: 4000

matrices:
  cross:
    deploy.gpu: "NVIDIA GeForce RTX 5090"
    deploy.gpu_count: 1
    zip:
      # Sweep larger context windows while dialing request concurrency to reduce OOM risk.
      # engine.llm.context_length: [32768, 32768, 65536, 102400]
      # engine.llm.max_concurrent_requests: [8, 12, 4, 1]
      engine.llm.context_length: [102400, 102400, 102400] # 114688, 131072
      engine.llm.max_concurrent_requests: [8, 12, 4]
      benchmark.max_concurrency: [8, 12, 4]
